#!/usr/bin/env node
const childProcess = require('node:child_process');
const pathUtils = require('../../src/Utils/path');

const child = childProcess.fork(pathUtils.join(__dirname, '../../cli'), [
   'runPreCommitHook'
], {});

child.on('exit', (code, signal) => {
   if (code !== 0) {
      console.log('Command "git commit" was rejected. Pre-commit hook finished with errors. See console or debug.log to path "./wasaby-cli_artifacts/runPreCommitHook/debug.log"');
   }

   process.exit(code);
});
